apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpr-deployment
  labels:
    app: mongoexpr-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongoexpr-app
  template:
    metadata:
      labels:
        app: mongoexpr-app
    spec:
      containers:
      - name: mongoexpr
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: url
                

        