apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQll6Q0NBUWdDQVFBd01ERXVNQ3dHQTFVRUF4TWxiWGt0Y0c5a0xtMTVMVzVoYldWemNHRmpaUzV3YjJRdQpZMngxYzNSbGNpNXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkltZU5xWUpmNktqClJrWVFkNjZ0NS9ZaVQ4UDNEdnk3YmtPQmNDZHdSMVl6NnZLNVJJQ01MS05kRHNrQ2FoajVxcUdLUytLNjZvQWoKZ1dNZ0l5dHFja09nZGpCMEJna3Foa2lHOXcwQkNRNHhaekJsTUdNR0ExVWRFUVJjTUZxQ0pXMTVMWE4yWXk1dAplUzF1WVcxbGMzQmhZMlV1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDSlcxNUxYQnZaQzV0ZVMxdVlXMWxjM0JoClkyVXVjRzlrTG1Oc2RYTjBaWEl1Ykc5allXeUhCTUFBQWhpSEJBb0FJZ0l3Q2dZSUtvWkl6ajBFQXdJRFNRQXcKUmdJaEFNNGQzVDMvZ0R2UDhONFpnWUxPL2lUREpyb2NhQWtMOUQxUjNxdDhObjBGQWlFQWtGQ3VWZWk1WkIwegp0NXllUlB4K1l5YlFxS25ncjA2MVBhaTc4U0xBeFlRPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: example.com/serving
  usages:
  - digital signature
  - key encipherment
  - server auth