apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
  labels:
    env: demo-rs
spec:
  template: 
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
  replicas: 4
  selector:
    matchLabels:
      env: demo